### ISSUE TITLE
Structure-specific mob spawning in skyblock

### ISSUE THREAD

**Issue by AlexProGear** [AntMCDev/MCSkyblock#7]
For some reason, structure specific spawns don't work as intended – witch huts don't spawn witches (but rather all the regular hostile mobs, even though they aren't allowed to spawn), ocean monuments don't spawn guardians etc.

I've tested the same modpack with skyblock/normal world type using the same seed, in a normal world it was working just fine.

It feels like the game doesn't know there is a structure – even though it's shown in F3 menu.

Here's a mod list, if you need it: https://pastebin.com/42wZYxk8

**Comment by AntMCDev** [comment]
Thanks for letting me know. It was a pretty tricky fix, but think I've got it all sorted. v2.0 has also been released over on Curseforge which should hopefully sort these issues. Given it a quick test and seems to work now from what I can see, but hard to test every combination of issues. In theory you won't need to start a new world, however it's worth noting that due to the way the logic works now - Swamp Huts will spawn around Y:0 (probably for the best, as that'll give the best spawn rates too). Again, thanks for letting me know

**Comment by AlexProGear** [comment]
I've tested it, mob spawns work fine now, thanks!
Though, witch huts spawn at y=0, but other structures (nether fortress, ocean monument) spawn at their respective heights.
I mean, it still works, but seems a bit inconsistent.
Also, witch farm designs mostly rely on making witches fall from their spawn point asap to make room for more spawns, which will not work at y=0. Guess, it's time to think about new designs :D

**Comment by AntMCDev** [comment]
I've just released v2.1 on Curseforge. Decided to add a new config option for this in the end - so you can choose between Y64 (the default), or Y0 now. Personally, I would use Y0 as you can use soul sand bubble elevators to raise the mobs upward, and then kill by fall damage that way - and you also get the increased spawn rates at the lower Y levels.

But yes, I agreed that it being inconsitent to the other structures was a bit strange. Doesn't help that minecraft has got tons of different ways of generating different strucutres (for example, swamp huts use the same logic as desert and jungle temples - and that's it, which is why it was inconsistent to other structures).

**Comment by AlexProGear** [comment]
Thank you, it works! :)
The issue is not the global mob caps (it's 70 for hostiles), but minecraft mob spawning logic.
"The mob's collision box upon spawning must not collide with another collision box. A mob cannot spawn inside of anything that would collide with it upon spawning."
Therefore, you should extract mobs asap for efficiency.
Source: https://minecraft.fandom.com/wiki/Spawn#Spawn_conditions

It's not like I'm really into technical minecraft, but I'm a bit inspired by people like ilmango.

**Comment by AntMCDev** [comment]
Yeah, the Scicraft guys are crazy good, haha. More of a case of whether it's faster to flush mobs using water streams into a bubble elevator outside the swamp hut bounds at Y:0 - thereby removing the issue with spawn collisions (thereby making full use of the faster spawn rates at lower Y levels); or whether it's faster to directly drop the mobs from a higher Y level (lower spawn rate, but the chance for spawn collisions to happen are lower). Think someone needs to do the math on that, haha
